[package]
name = "mnemosyne-prof"
license = "MIT OR Apache-2.0"
version = "0.2.0"
edition = "2024"
rust-version = "1.95"
repository.workspace = true
description = "Allocation profiling support for Mnemosyne"
homepage.workspace = true
readme = "README.md"
keywords = ["allocator", "profiling", "heap", "leak-detection", "memory"]
categories = ["memory-management", "development-tools::profiling"]

[dependencies]
mnemosyne-core = { package = "mnemosyne-memory-core", path = "../mnemosyne-core", version = "0.2.0" }
backtrace = "0.3"

[build-dependencies]
mnemosyne-build-util = { path = "../mnemosyne-build-util", version = "0.2.0" }

[features]
nightly_tls = []
std_tls = []

[dev-dependencies]
mnemosyne = { package = "mnemosyne-memory", path = "../mnemosyne" }
mnemosyne-local = { path = "../mnemosyne-local" }
mnemosyne-heap = { path = "../mnemosyne-heap" }
mnemosyne-backend = { path = "../mnemosyne-backend" }

[lints]
workspace = true
